### ISSUE TITLE
Program closes when loading a chart

### ISSUE THREAD

**Issue by Connormgs** [krrcream/krr-s-osumania-anyKeys-converter#2]
Hello, 

I downloaded your tool and whenever I drag a .osu chart into the tool it just closes with no error. Is there any sort of error logging I could enable to help with troubleshooting?

**Comment by HowieHz** [comment]
Thanks for your feedback.
Can you drag this tool on cmd/powershell and run it. It may show you some error.

**Comment by krrcream** [comment]
As a beginner in programming, I apologize for my current inability to troubleshoot these issues. However, there are two known problems at the moment. Firstly, audio files and background files name may encounter errors if they contain certain symbols, such as single quotes ' in background filename. These files need to be renamed (includeed in .osu file) to resolve the issue. Secondly, the chart format is not standard, such as the bms converted by Davteezy and Doorknob. You will need to save it again in osu editor to fix this(just press Ctrl+S).

Regarding the first problem, I will try to find a solution later. For the second issue, since the .osu file text format is different, it might not be possible to solve it directly. In the future, I plan to create a feature that can pop up error messages when encountering such issues.

**Comment by krrcream** [comment]
Version 0.8 has already been released.
Although I haven't completed the error logging feature yet, I've fixed most of the bugs that would cause the program to crash.   There's still a small portion that is beyond my current capability to repair.   I discovered some incorrectly formatted [metadata] and some incorrectly formatted notes , which don't match the current official .osu file format.   The only solution for this is to refresh the file format by resaving it in the game.   And given that batch conversion can result in hundreds or even thousands of .osu files, I realized that a single pop-up window would be unable to display all the content,so I implemented a feature to skip the unsolvable errors.

**Comment by krrcream** [comment]
Version 0.8 has already been released.
Although I haven't completed the error logging feature yet, I've fixed most of the bugs that would cause the program to crash.   There's still a small portion that is beyond my current capability to repair.   I discovered some incorrectly formatted [metadata] and some incorrectly formatted notes , which don't match the current official .osu file format.   The only solution for this is to refresh the file format by resaving it in the game.   And given that batch conversion can result in hundreds or even thousands of .osu files, I realized that a single pop-up window would be unable to display all the content,so I implemented a feature to skip the unsolvable errors.

Fixed some [HitObjects] formatting issues, allowing the program to correctly handle some special beatmap files(other converter's layout).  
like this:
 "192,192,9974,1,0"
 " "
 "100,100,12600,6,1,B|200:200|250:200|250:200|300:150,2,310.123,2|1|2,0:0|0:0|0:2,0:0:0:0:"
 "155.60000000000002,192,17423,128,0,17659:0:0:0:0:"
